### ISSUE TITLE
哔哩轻小说设置防盗之后输出的文字有误

### ISSUE THREAD

**Issue by yuduotianguang** [Montaro2017/bili_novel_packer#11]

**Comment by yuduotianguang** [comment]
我刚关代理重下的，还是这样


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Montaro2017/bili_novel_packer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月31日(星期一) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Montaro2017/bili_novel_packer] 哔哩轻小说设置防盗之后输出的文字有误 (Issue #11)





 
没有复现，检查下是否是你设置了代理之类的

**Comment by Montaro2017** [comment]
https://w.linovelib.com/novel/2013/72035.html
你打开这个网址看一下内容能不能正常显示，有没有弹什么验证之类的

**Comment by yuduotianguang** [comment]
> https://w.linovelib.com/novel/2013/72035.html
> 你打开这个网址看一下内容能不能正常显示，有没有弹什么验证之类的

网页倒是可以正常显示
这个也试了，全是防盗，而且图片也显示不了

**Comment by Montaro2017** [comment]
看起来是文字问题被特殊字符替换后通过js还原了，js做了混淆，分析需要时间

**Comment by Montaro2017** [comment]
[v0.1.5](https://github.com/Montaro2017/bili_novel_packer/releases/tag/v0.1.5)
看一下 应该没问题了
