### ISSUE TITLE
按回车后闪退。哔哩轻小说换域名了，可以改一下。希望增加真白萌(masiro.me)。感谢

### ISSUE THREAD

**Issue by yuduotianguang** [Montaro2017/bili_novel_packer#12]

**Comment by yuduotianguang** [comment]
emmm，闪退是因为用的新域名

**Comment by Montaro2017** [comment]
实测没问题，没有更换域名

**Comment by yuduotianguang** [comment]
啊这，一个哩哔一个哔哩，东西倒是一样，但是后面的电脑端好看点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Montaro2017/bili_novel_packer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 晚上9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Montaro2017/bili_novel_packer] 按回车后闪退。哔哩轻小说换域名了，可以改一下。希望增加真白萌(masiro.me)。感谢 (Issue #12)





 
实测没问题，没有更换域名

**Comment by Montaro2017** [comment]
masiro.me暂时不增加了，建议PR
