### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by watercup0926** [Montaro2017/bili_novel_packer#13]
### 使用版本
使用版本: 0.1.5 (请使用最新版尝试是否仍有问题)

### 复现步骤

1. 输入网址：https://www.wenku8.net/book/3167.htm
2. 选择分卷：沒有回應
3. 错误信息：错误信息截图
![image](https://github.com/Montaro2017/bili_novel_packer/assets/112764394/7653d21a-3a8e-4e78-a167-e51342265ded)

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息

**Comment by watercup0926** [comment]
這個不急，只是看到可以用文庫就手賤用一下

**Comment by Montaro2017** [comment]
不知道什么问题，重新编译一下就好了，重新下载0.1.5版本
