### ISSUE TITLE
[BUG] 开始打包时闪退

### ISSUE THREAD

**Issue by yuezhuosc** [Montaro2017/bili_novel_packer#15]
### 使用版本
使用版本: 0.1.6 (请使用最新版尝试是否仍有问题)

### 复现步骤

1. 输入网址：https://w.linovelib.com/novel/3848.html（事实上这里无论输入哪本书都是一样的）
2. 选择分卷：闪退
3. 错误信息：错误信息截图
![0cd0e9b316a8791aa5f3b6a011d3de4](https://github.com/Montaro2017/bili_novel_packer/assets/75358283/57e67249-fa3e-4e17-a48f-6338aa946ee6)
在此界面按下回车后，显示正在打包第一卷，然后立刻闪退。

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息
没有显示错误信息。

**Comment by Montaro2017** [comment]
0.1.7修复
