### ISSUE TITLE
[BUG] 輕小說文庫無法下載

### ISSUE THREAD

**Issue by watercup0926** [Montaro2017/bili_novel_packer#16]
### 使用版本
使用版本: 0.1.7 (请使用最新版尝试是否仍有问题)

### 复现步骤

1. 输入网址：https://www.wenku8.net/book/3067.htm
2. 选择分卷：全部
3. 错误信息：
![image](https://github.com/Montaro2017/bili_novel_packer/assets/112764394/b69d0cd6-e17d-4a98-ba67-b14dfb2a0d83)

沒有報錯
如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息

**Comment by Montaro2017** [comment]
不知道是不是依赖库问题，使用IDE运行没有问题，用编译后的可执行文件就会有问题

**Comment by Montaro2017** [comment]
新版本修复
