### ISSUE TITLE
[BUG] 0.26版本输入网址后闪退

### ISSUE THREAD

**Issue by harrylisen** [Montaro2017/bili_novel_packer#17]
### 使用版本
使用版本: 0.2.6 (请使用最新版尝试是否仍有问题)

### 复现步骤

1. 输入网址：http://w.linovelib.com/novel/1.html
2. 闪退

错误信息如下
![image](https://github.com/Montaro2017/bili_novel_packer/assets/46640121/f6ae3d48-130c-415f-a880-750bad16b161)

**Comment by Montaro2017** [comment]
见 [I8MSH2](https://gitee.com/Montaro2017/bili_novel_packer/issues/I8MSH2)

**Comment by Montaro2017** [comment]
见 [I8MSH2](https://gitee.com/Montaro2017/bili_novel_packer/issues/I8MSH2)

**Comment by Montaro2017** [comment]
0.2.7现已支持bilinovel.com

**Comment by harrylisen** [comment]
谢谢！
