### ISSUE TITLE
哔哩轻小说网站目前不支持电脑端了，做出的epub只有图无正文，还有办法么

### ISSUE THREAD

**Issue by yuduotianguang** [Montaro2017/bili_novel_packer#19]
备用站无法阅读主站可以，但是用主站网址一样无正文

**Comment by yuduotianguang** [comment]
以及轻小说文库，有些无法打包，原因不明，测试的是邻家天使第一卷

**Comment by Montaro2017** [comment]
测试正常

**Comment by yuduotianguang** [comment]
好吧是koodo reader的问题，但是轻小说文库的邻家天使第一卷还是无法打包，中途闪退。以及现在打包完成只有退出选项了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Montaro2017/bili_novel_packer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 上午8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Montaro2017/bili_novel_packer] 哔哩轻小说网站目前不支持电脑端了，做出的epub只有图无正文，还有办法么 (Issue #19)





 
测试正常

**Comment by Montaro2017** [comment]
不要让我在重复说，提供url和版本号
