### ISSUE TITLE
[BUG] 显示开始打包后，出现报错

### ISSUE THREAD

**Issue by NineMeowICT** [Montaro2017/bili_novel_packer#20]
### 使用版本
使用版本: 0.2.9 (请使用最新版尝试是否仍有问题)

### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/2986.html
2. 选择分卷：全部
3. 错误信息：
![image](https://github.com/Montaro2017/bili_novel_packer/assets/115801669/0e6fce0b-4ddc-4964-bad6-8158eea91184)

多次尝试都一样

**Comment by Montaro2017** [comment]
重复的
