### ISSUE TITLE
[BUG] 显示开始打包后，出现报错

### ISSUE THREAD

**Issue by NineMeowICT** [Montaro2017/bili_novel_packer#21]
### 使用版本
使用版本: 0.2.9 (请使用最新版尝试是否仍有问题)

### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/2986.html
2. 选择分卷：全部
3. 错误信息：
![image](https://github.com/Montaro2017/bili_novel_packer/assets/115801669/0e6fce0b-4ddc-4964-bad6-8158eea91184)

多次尝试都一样，本人没学过Dart所以没法进一步Debug，麻烦大佬了

顺带一提，使用时有概率出现Unhandled exception:
ClientException: Connection closed before full header was received, uri=https://www.bilinovel.com/themes/zhmb/js/readtool.js，
但是在浏览器打开该网址正常（确认非缓存），我一开始还以为是代理的锅，结果确认即使完全不走代理也有几率出现这样的错误

**Comment by Montaro2017** [comment]
你用的是哪个版本

**Comment by Montaro2017** [comment]
测试正常，是不是网络不稳定
![image](https://github.com/Montaro2017/bili_novel_packer/assets/35142778/bcb1aca1-e3ab-4c8a-a8cc-11a7119eb6a5)

**Comment by NineMeowICT** [comment]
> 你用的是哪个版本

就是最新版

**Comment by NineMeowICT** [comment]
> 测试正常，是不是网络不稳定 ![image](https://private-user-images.githubusercontent.com/35142778/296466454-bcb1aca1-e3ab-4c8a-a8cc-11a7119eb6a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODk5MTksIm5iZiI6MTcwNTE4OTYxOSwicGF0aCI6Ii8zNTE0Mjc3OC8yOTY0NjY0NTQtYmNiMWFjYTEtZTNhYi00YzhhLWE4Y2MtMTFhNzExOWViNmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIzNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWNiY2VmM2U1MTU5NjljODFlM2EyZGQ2MjIyY2FhYmJjZjE3NjQzYTBhOWQwNWY4NmQyMDdhMDg0OWNhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l538OGgOzBSb_qLT3-R79GmB7h-ElLCPPTiKFaHhSXo)

@Montaro2017 今天用再次出现Null check operator used on a null value
希望你能稍微解释下这个报错是怎么出现的，也许我就能找到自己环境问题所在了，谢谢！

**Comment by Montaro2017** [comment]
> > 测试正常，是不是网络不稳定 ![image](https://private-user-images.githubusercontent.com/35142778/296466454-bcb1aca1-e3ab-4c8a-a8cc-11a7119eb6a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODk5MTksIm5iZiI6MTcwNTE4OTYxOSwicGF0aCI6Ii8zNTE0Mjc3OC8yOTY0NjY0NTQtYmNiMWFjYTEtZTNhYi00YzhhLWE4Y2MtMTFhNzExOWViNmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIzNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWNiY2VmM2U1MTU5NjljODFlM2EyZGQ2MjIyY2FhYmJjZjE3NjQzYTBhOWQwNWY4NmQyMDdhMDg0OWNhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l538OGgOzBSb_qLT3-R79GmB7h-ElLCPPTiKFaHhSXo)
> 
> @Montaro2017 今天用再次出现Null check operator used on a null value 希望你能稍微解释下这个报错是怎么出现的，也许我就能找到自己环境问题所在了，谢谢！ 输入网址：https://www.bilinovel.com/novel/2841.html
> 
> 昨天调整代理设置后，Connection closed before full header was received没出现过了，但前面那个报错还是可能会有

这种问题是因为获取到的网页元素取为空，相当于空指针异常

**Comment by NineMeowICT** [comment]
> 这种问题是因为获取到的网页元素取为空，相当于空指针异常

我已经被搞糊涂了，fiddler抓不到程序进行抓取时的https包，用wireshark监听倒是可以看到正常的Client Hello，TLS1.3和TCP包收发看起来也都正常，IP地址也和浏览器访问时的一致，加载小说元数据一直正常，但就是没法正常抓取小说内容（之前偶然成功抓取过一次，无法复现，改天上Linux试试）

话说Dart没必要能交叉编译啊，要Build&Release其他平台的binary只要用GitHub的Action Workflow配置所需平台的构建流程就行了

**Comment by Montaro2017** [comment]
> > 这种问题是因为获取到的网页元素取为空，相当于空指针异常
> 
> 我已经被搞糊涂了，fiddler抓不到程序进行抓取时的https包，用wireshark监听倒是可以看到正常的Client Hello，TLS1.3和TCP包收发看起来也都正常，IP地址也和浏览器访问时的一致，加载小说元数据一直正常，但就是没法正常抓取小说内容（之前偶然成功抓取过一次，无法复现，有点怀疑是我软件环境配置的问题，改天上Linux试试）
> 
> 话说Dart没必要能交叉编译啊，要Build&Release其他平台的binary只要用GitHub的Action Workflow配置所需平台的构建流程不就行了？

终端默认应该是不走代理的，你试试
```
set http_proxy=localhost:8888
set https_proxy=localhost:8888
```

**Comment by NineMeowICT** [comment]
> set http_proxy=localhost:8888
> set https_proxy=localhost:8888
> ```
> 
> 然后在终端里面启动

是我故意不让他走代理的，因为哔哩本来就能直连
之前我有设代理环境变量的时候会有概率出现ClientException: Connection closed before full header was received，删了之后才好的
