### ISSUE TITLE
[BUG] 最新的.12打包到最后会一直报错，老版的11也是一样

### ISSUE THREAD

**Issue by boom-aligetgetboom-aligetget** [Montaro2017/bili_novel_packer#23]
如图

![I%5I_{(TQ~%$M9%4AGANLZC](https://github.com/Montaro2017/bili_novel_packer/assets/53316853/9f631d9a-6c1b-4aa0-a4b1-ab72b7c58d44)

**Comment by Montaro2017** [comment]
网址，第几卷

**Comment by boom-aligetgetboom-aligetget** [comment]
> 网址，第几卷

https://www.bilinovel.com/novel/3614.html，就一单卷的
