### ISSUE TITLE
下载的内容不对

### ISSUE THREAD

**Issue by qycqycqyc** [Montaro2017/bili_novel_packer#24]
内容全是：﹏ò)
抱歉，章节内容不支持该浏览器显示～
【为了使用完整的阅读功能】
请考虑使用〔Chrome 谷歌浏览器〕、〔Safari 苹果浏览器〕或者〔Edge 微软浏览器〕等原生浏览器阅读！
谢谢!!!

**Comment by Montaro2017** [comment]
网站加密更新了，难搞，我在研究
