### ISSUE TITLE
[BUG] 使用版本 0.2.14无法下载哔哩轻小说,

### ISSUE THREAD

**Issue by eiauo** [Montaro2017/bili_novel_packer#26]
### 使用版本
使用版本:  0.2.14

### 复现步骤

1. 输入网址：http://w.linovelib.com/novel/1.html
2. 选择分卷：全部
3. 错误信息：错误信息截图
![packer](https://github.com/Montaro2017/bili_novel_packer/assets/16713174/e439fe9b-8616-49c3-bb9a-cab5325c9061)

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息

**Comment by Arashimu** [comment]
> 我这边没有问题，看你是否可以查看第一卷

我也遇到了同样的问题

**Comment by Montaro2017** [comment]
应该是IP问题，这个我无法解决
