### ISSUE TITLE
比例轻小说有部分乱码

### ISSUE THREAD

**Issue by weijingcheng4** [Montaro2017/bili_novel_packer#28]
### 使用版本
使用版本: 0.2.15

### 复现步骤

1. 输入网址：https://www.linovelib.com/novel/2014/72468_9.html
2. 选择分卷：全部
3. 错误信息：错误信息截图

![01867CEC56BC42BBA4502B9603E10958](https://github.com/Montaro2017/bili_novel_packer/assets/49937971/e020ea6e-ede5-48d6-a788-393464f99e10)

![600E87E7C0F99C0E6403D58FA6F66DC5](https://github.com/Montaro2017/bili_novel_packer/assets/49937971/e63c2bfe-898d-4542-8d49-daabe1c69a75)

**Comment by Montaro2017** [comment]
这是第几卷 第几章

**Comment by weijingcheng4** [comment]
《OVERLORD不死者之王》 
第十二卷 圣王国的圣骑士（上）
第一章 魔皇亚达巴沃（9/9）

**Comment by Montaro2017** [comment]
0.2.16解决了，点个star吧，解决这问题真不容易
