### ISSUE TITLE
0.1.1 .exe無法下載特定小說

### ISSUE THREAD

**Issue by watercup0926** [Montaro2017/bili_novel_packer#3]
https://tw.linovelib.com/novel/2139.html
下載時，選完是否為每張添加標題CMD直接關閉

**Comment by watercup0926** [comment]
另外一個例子
https://tw.linovelib.com/novel/6.html
第13.5卷

**Comment by Montaro2017** [comment]
https://tw.linovelib.com/novel/2139.html 这个是文件名处理有问题
https://tw.linovelib.com/novel/6.html 这个是图片太多导致下载超时问题，当初就没考虑会有人用来下漫画...

**Comment by Montaro2017** [comment]
文件名的问题应该解决了 https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/0.1.2

**Comment by watercup0926** [comment]
抱歉，腦洞開太大了

**Comment by Montaro2017** [comment]
> 抱歉，腦洞開太大了

不，这确实是一个问题

**Comment by watercup0926** [comment]
re0的短篇集跟第9卷也有問題

**Comment by Montaro2017** [comment]
> re0的短篇集跟第9卷也有問題

https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/0.1.2-M1

**Comment by watercup0926** [comment]
https://tw.linovelib.com/novel/2668.html
第一卷

**Comment by watercup0926** [comment]
https://tw.linovelib.com/novel/2544.html
第8卷

**Comment by watercup0926** [comment]
https://tw.linovelib.com/novel/8.html
第一卷

**Comment by watercup0926** [comment]
https://tw.linovelib.com/novel/1509.html
第一卷

**Comment by Montaro2017** [comment]
问题已经清楚了，报错信息
```
Unhandled exception:
TimeoutException after 0:00:03.000000: Future not completed
```
不过这个报错连堆栈都没有，不知道是哪报的错，有点棘手

**Comment by watercup0926** [comment]
https://tw.linovelib.com/novel/2198.html
地8捲

**Comment by watercup0926** [comment]
https://tw.linovelib.com/novel/2271.html
第20捲

**Comment by Montaro2017** [comment]
试试[0.1.2-M4版本](https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/v0.1.2-M4)

**Comment by watercup0926** [comment]
我找到了幾本書有問題，請大佬慢慢來，不急

**Comment by Montaro2017** [comment]
> 我找到了幾本書有問題，請大佬慢慢來，不急

你再试试吧，我把你发的链接基本都试了一遍，好像又没有问题了，可能这个问题偶尔会出现

**Comment by Montaro2017** [comment]
[0.1.2-M7](https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/v0.1.2-M7)
这个版本应该能解决了吧

**Comment by Montaro2017** [comment]
@svdbnm

**Comment by watercup0926** [comment]
謝謝大佬，我會找更多bug回來的
