### ISSUE TITLE
[BUG] 使用版本 0.2.17无法下载哔哩轻小说

### ISSUE THREAD

**Issue by eiauo** [Montaro2017/bili_novel_packer#30]
### 使用版本
使用版本:  0.2.17

### 复现步骤

1. 输入网址：http://w.linovelib.com/novel/1.html
2. 选择分卷：全部
3. 错误信息：错误信息截图
![ju](https://github.com/Montaro2017/bili_novel_packer/assets/16713174/e875fc37-f404-4deb-8ba5-33e864d098af)

使用代理也是同样的问题，使用Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"

**Comment by Montaro2017** [comment]
复现不了

**Comment by Montaro2017** [comment]
你可以正常打开http://www.bilinovel.com/novel/1.html吗，PC打开会重定向到linovelib，要保证UA是移动端UA
还有你的IP是哪个地区的

**Comment by xingxiacha** [comment]
出现了同样的问题，IP是浙江省，用的香港的梯子

**Comment by xingxiacha** [comment]
> 你可以正常打开http://www.bilinovel.com/novel/1.html 吗，PC打开会重定向到linovelib，要保证UA是移动端UA 还有你的IP是哪个地区的 
可以正常打开并阅读，IP是浙江

**Comment by xingxiacha** [comment]
可以正常打开网页

**Comment by Montaro2017** [comment]
> 出现了同样的问题，IP是浙江省，用的香港的梯子

不要用梯子，bilinovel会屏蔽海外IP。
另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com

**Comment by xingxiacha** [comment]
> > 出现了同样的问题，IP是浙江省，用的香港的梯子
> 
> 不要用梯子，bilinovel会屏蔽海外IP。
> 另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com

这次没有用梯子，打开的也是bilinovel.com,但还是遇到了一样的问题![6}7SFQRRA6YYVGVY~1A3TZB(1).png](https://github.com/Montaro2017/bili_novel_packer/assets/114482558/f88168dd-a88c-4e41-af84-eee22e05eb26)

![CYDJCO(SGLS)U3EC@FVPRMW.png](https://github.com/Montaro2017/bili_novel_packer/assets/114482558/284cdb69-8869-47b0-9552-60ba208ca32e)

**Comment by Montaro2017** [comment]
> > > 出现了同样的问题，IP是浙江省，用的香港的梯子
> > 
> > 
> > 不要用梯子，bilinovel会屏蔽海外IP。
> > 另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com
> 
> 这次没有用梯子，打开的也是bilinovel.com,但还是遇到了一样的问题![6}7SFQRRA6YYVGVY~1A3TZB(1).png](https://private-user-images.githubusercontent.com/114482558/331954449-f88168dd-a88c-4e41-af84-eee22e05eb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDQ5LWY4ODE2OGRkLWE4OGMtNGU0MS1hZjg0LWVlZTIyZTA1ZWIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTExMzJiZDJhYjE4MWJhNTA0NmU3MjZlMjVmNmJkZDU2ZWZhNjIwZDg0Y2E2MzIxYTE4N2IzZjU0OWRjZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UG7GfBD9vX-lfzlvIZixsObd1JM4OmXAepofi1xLF6Y)
> 
> ![CYDJCO(SGLS)U3EC@FVPRMW.png](https://private-user-images.githubusercontent.com/114482558/331954461-284cdb69-8869-47b0-9552-60ba208ca32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDYxLTI4NGNkYjY5LTg4NjktNDdiMC05NTUyLTYwYmEyMDhjYTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTQzMzRlYWYxYjZkNjY5NWExYmI4ZGZlMGM1NjYwNDkwZjdhZDMzY2NiMDY4NDJiMDNmNzAxMzAzNmE2NzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5aqTYeVMo8vCHwvMER1w6dseCU9EBE7hII-IkGOyOvc)

你要点进章节才会自动跳转

**Comment by xingxiacha** [comment]
> > > > 出现了同样的问题，IP是浙江省，用的香港的梯子
> > > 
> > > 
> > > 不要用梯子，bilinovel会屏蔽海外IP。
> > > 另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com
> > 
> > 这次没有用梯子，打开的也是bilinovel.com,但还是遇到了一样的问题![6}7SFQRRA6YYVGVY~1A3TZB(1).png](https://private-user-images.githubusercontent.com/114482558/331954449-f88168dd-a88c-4e41-af84-eee22e05eb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDQ5LWY4ODE2OGRkLWE4OGMtNGU0MS1hZjg0LWVlZTIyZTA1ZWIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTExMzJiZDJhYjE4MWJhNTA0NmU3MjZlMjVmNmJkZDU2ZWZhNjIwZDg0Y2E2MzIxYTE4N2IzZjU0OWRjZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UG7GfBD9vX-lfzlvIZixsObd1JM4OmXAepofi1xLF6Y)
> > 
> > ![CYDJCO(SGLS)U3EC@FVPRMW.png](https://private-user-images.githubusercontent.com/114482558/331954461-284cdb69-8869-47b0-9552-60ba208ca32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDYxLTI4NGNkYjY5LTg4NjktNDdiMC05NTUyLTYwYmEyMDhjYTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTQzMzRlYWYxYjZkNjY5NWExYmI4ZGZlMGM1NjYwNDkwZjdhZDMzY2NiMDY4NDJiMDNmNzAxMzAzNmE2NzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5aqTYeVMo8vCHwvMER1w6dseCU9EBE7hII-IkGOyOvc)
> 
> 你要点进章节才会自动跳转

还真是，那怎么阻止它跳转呢？

**Comment by Montaro2017** [comment]
> > > > > 出现了同样的问题，IP是浙江省，用的香港的梯子
> > > > 
> > > > 
> > > > 不要用梯子，bilinovel会屏蔽海外IP。
> > > > 另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com
> > > 
> > > 
> > > 这次没有用梯子，打开的也是bilinovel.com,但还是遇到了一样的问题![6}7SFQRRA6YYVGVY~1A3TZB(1).png](https://private-user-images.githubusercontent.com/114482558/331954449-f88168dd-a88c-4e41-af84-eee22e05eb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDQ5LWY4ODE2OGRkLWE4OGMtNGU0MS1hZjg0LWVlZTIyZTA1ZWIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTExMzJiZDJhYjE4MWJhNTA0NmU3MjZlMjVmNmJkZDU2ZWZhNjIwZDg0Y2E2MzIxYTE4N2IzZjU0OWRjZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UG7GfBD9vX-lfzlvIZixsObd1JM4OmXAepofi1xLF6Y)
> > > ![CYDJCO(SGLS)U3EC@FVPRMW.png](https://private-user-images.githubusercontent.com/114482558/331954461-284cdb69-8869-47b0-9552-60ba208ca32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDYxLTI4NGNkYjY5LTg4NjktNDdiMC05NTUyLTYwYmEyMDhjYTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTQzMzRlYWYxYjZkNjY5NWExYmI4ZGZlMGM1NjYwNDkwZjdhZDMzY2NiMDY4NDJiMDNmNzAxMzAzNmE2NzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5aqTYeVMo8vCHwvMER1w6dseCU9EBE7hII-IkGOyOvc)
> > 
> > 
> > 你要点进章节才会自动跳转
> 
> 还真是，那怎么阻止它跳转呢？

谷歌浏览器用这个插件 https://chromewebstore.google.com/detail/einpaelgookohagofgnnkcfjbkkgepnp
然后用下面这个UA
`Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36`

**Comment by xingxiacha** [comment]
> > > > > > 出现了同样的问题，IP是浙江省，用的香港的梯子
> > > > > 
> > > > > 
> > > > > 不要用梯子，bilinovel会屏蔽海外IP。
> > > > > 另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com
> > > > 
> > > > 
> > > > 这次没有用梯子，打开的也是bilinovel.com,但还是遇到了一样的问题![6}7SFQRRA6YYVGVY~1A3TZB(1).png](https://private-user-images.githubusercontent.com/114482558/331954449-f88168dd-a88c-4e41-af84-eee22e05eb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDQ5LWY4ODE2OGRkLWE4OGMtNGU0MS1hZjg0LWVlZTIyZTA1ZWIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTExMzJiZDJhYjE4MWJhNTA0NmU3MjZlMjVmNmJkZDU2ZWZhNjIwZDg0Y2E2MzIxYTE4N2IzZjU0OWRjZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UG7GfBD9vX-lfzlvIZixsObd1JM4OmXAepofi1xLF6Y)
> > > > ![CYDJCO(SGLS)U3EC@FVPRMW.png](https://private-user-images.githubusercontent.com/114482558/331954461-284cdb69-8869-47b0-9552-60ba208ca32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDYxLTI4NGNkYjY5LTg4NjktNDdiMC05NTUyLTYwYmEyMDhjYTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTQzMzRlYWYxYjZkNjY5NWExYmI4ZGZlMGM1NjYwNDkwZjdhZDMzY2NiMDY4NDJiMDNmNzAxMzAzNmE2NzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5aqTYeVMo8vCHwvMER1w6dseCU9EBE7hII-IkGOyOvc)
> > > 
> > > 
> > > 你要点进章节才会自动跳转
> > 
> > 还真是，那怎么阻止它跳转呢？
> 
> 谷歌浏览器用这个插件 https://chromewebstore.google.com/detail/einpaelgookohagofgnnkcfjbkkgepnp
> 然后用下面这个UA
> `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36`

这次没有自动跳转了，但还是报错

![[F6Q_E88P11[BCY(71[9U]M.png](https://github.com/Montaro2017/bili_novel_packer/assets/114482558/d39afa83-6a39-44e1-8f1a-750422f7c341)

![T~Y5[KTA_)U0XK7`)PHXAMT.png](https://github.com/Montaro2017/bili_novel_packer/assets/114482558/fe06e8d2-c449-4af0-829a-956dbfe47b2d)

**Comment by xingxiacha** [comment]
> > > > > > 出现了同样的问题，IP是浙江省，用的香港的梯子
> > > > > 
> > > > > 
> > > > > 不要用梯子，bilinovel会屏蔽海外IP。
> > > > > 另外确定你打开的是bilinovel.com而不是自动跳转到linovelib.com
> > > > 
> > > > 
> > > > 这次没有用梯子，打开的也是bilinovel.com,但还是遇到了一样的问题![6}7SFQRRA6YYVGVY~1A3TZB(1).png](https://private-user-images.githubusercontent.com/114482558/331954449-f88168dd-a88c-4e41-af84-eee22e05eb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDQ5LWY4ODE2OGRkLWE4OGMtNGU0MS1hZjg0LWVlZTIyZTA1ZWIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTExMzJiZDJhYjE4MWJhNTA0NmU3MjZlMjVmNmJkZDU2ZWZhNjIwZDg0Y2E2MzIxYTE4N2IzZjU0OWRjZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UG7GfBD9vX-lfzlvIZixsObd1JM4OmXAepofi1xLF6Y)
> > > > ![CYDJCO(SGLS)U3EC@FVPRMW.png](https://private-user-images.githubusercontent.com/114482558/331954461-284cdb69-8869-47b0-9552-60ba208ca32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODM3OTUsIm5iZiI6MTcxNjE4MzQ5NSwicGF0aCI6Ii8xMTQ0ODI1NTgvMzMxOTU0NDYxLTI4NGNkYjY5LTg4NjktNDdiMC05NTUyLTYwYmEyMDhjYTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTQzMzRlYWYxYjZkNjY5NWExYmI4ZGZlMGM1NjYwNDkwZjdhZDMzY2NiMDY4NDJiMDNmNzAxMzAzNmE2NzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5aqTYeVMo8vCHwvMER1w6dseCU9EBE7hII-IkGOyOvc)
> > > 
> > > 
> > > 你要点进章节才会自动跳转
> > 
> > 
> > 还真是，那怎么阻止它跳转呢？
> 
> 谷歌浏览器用这个插件 https://chromewebstore.google.com/detail/einpaelgookohagofgnnkcfjbkkgepnp 然后用下面这个UA `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36`

这次没有自动跳转，但还是报同样的错
![T~Y5 KTA_)U0XK7`)PHXAMT](https://github.com/Montaro2017/bili_novel_packer/assets/114482558/b217257b-ee50-4e4c-ae83-57de85ebb76e)
![F6Q_E88P11 BCY(71 9U M](https://github.com/Montaro2017/bili_novel_packer/assets/114482558/7f9d8374-dd5f-47e1-b7c7-da5347d6f25a)

**Comment by 147258-gif** [comment]
0.2.18，在设置安卓ua后，出现同样问题
![Snipaste_2024-06-17_12-34-30](https://github.com/Montaro2017/bili_novel_packer/assets/58428549/d0a09a7b-6504-4ba5-817f-cb51d0f73fc6)

**Comment by Zhong98** [comment]
bilinovel是不是更新反爬机制了，现在0.2.18下不了，一直null value，IP也在国内

**Comment by Highwe2hell** [comment]
貌似是部分小说会这样，有的小说下载的时候又不会有问题，头疼。

**Comment by NineMeowICT** [comment]
+1
几个星期前linux下编译了0.2.17，正常下载，无代理
刚刚编译了0.2.18，一样的网络环境，出现该issue同样错误

**Comment by eiauo** [comment]
已经可以下载完整小说。赞
