### ISSUE TITLE
[BUG] 下载哔哩轻小说时最后一句话是乱码

### ISSUE THREAD

**Issue by Neight99** [Montaro2017/bili_novel_packer#31]
### 使用版本
使用版本:  0.2.17

### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/3906.html
2. 选择分卷：2-05
3. 错误信息：有多页的章节最后一段话会是乱码
 
![image](https://github.com/Montaro2017/bili_novel_packer/assets/32681608/cb4fcb03-7e52-4f72-b8b3-d2006b9ab657)

**Comment by Montaro2017** [comment]
网页上就是乱码
![image](https://github.com/Montaro2017/bili_novel_packer/assets/35142778/aa61558b-9067-492b-98ad-0fefb5494964)

**Comment by Neight99** [comment]
我在win11系统下用edge浏览器打开，最后这句不是乱码，感觉是有特殊的样式？

**Comment by Montaro2017** [comment]
> 我在win11系统下用edge浏览器打开，最后这句不是乱码，感觉是有特殊的样式？

因为程序用的是移动端的域名，你浏览器打开会自动重定向到PC端的域名，PC端和移动端表现不一致

**Comment by Montaro2017** [comment]
> 我在win11系统下用edge浏览器打开，最后这句不是乱码，感觉是有特殊的样式？

你用浏览器打开会自动跳转到PC端，PC端和移动端表现不一致，程序用的是移动端域名

![image](https://github.com/Montaro2017/bili_novel_packer/assets/35142778/46ca93b7-af1d-486b-9ebe-5ee9d23f73f9)

**Comment by Montaro2017** [comment]
你如果在意可以用sigil编辑一下
