### ISSUE TITLE
[BUG] 0.2.17无法下载哔哩轻小说

### ISSUE THREAD

**Issue by Zhong98** [Montaro2017/bili_novel_packer#32]
### 使用版本
使用版本:  0.2.17

### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/3765.html
2. 选择分卷：无法选择分卷，会直接出现运行错误
3. 错误信息：错误信息截图
<img width="780" alt="屏幕截图 2024-05-16 145135" src="https://github.com/Montaro2017/bili_novel_packer/assets/91147077/6929b256-c44e-45b4-9374-43bd5ba875b4">

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息

**Comment by Montaro2017** [comment]
多试几次
