### ISSUE TITLE
有冇可能加繁體中文支援?

### ISSUE THREAD

**Issue by AIizss** [Montaro2017/bili_novel_packer#33]
有冇可能加繁體中文支援? 在嗶哩輕小說裡有一個選項可以從簡體中文更改為繁體中文
google translate: 有冇可能加繁体中文支援？ 在哔哩轻小说里有一个选项可以从简体中文更改为繁体中文
![Screenshot 2024-06-01 045748](https://github.com/Montaro2017/bili_novel_packer/assets/171400804/254fbb7d-89fe-4954-931f-7281452bf798)

**Comment by Montaro2017** [comment]
如果要增加繁简转换的功能，需要增加新的选项，目前是CLI方式交互，我不太希望有太多选项，这样得选好多次，如果有什么好的交互方式可以考虑下。
当初选择dart的理由就是如果用flutter写可以复用代码，写成GUI加多个选项都没关系，当然那得等我先学会flutter再说。

**Comment by Montaro2017** [comment]
繁简转换可能并不是一个容易实现的功能，建议专业工具转换生成后的EPUB，目前暂不考虑添加此功能。

**Comment by 2655196510** [comment]
可以自己转换，这里有个转换网站
https://v.magiconch.com/epub-transform.html#:~:text=%E9%98%85%E8%AF%BB%20ePub
