### ISSUE TITLE
[BUG] 无法正确加载目录

### ISSUE THREAD

**Issue by Highwe2hell** [Montaro2017/bili_novel_packer#36]
### 使用版本
使用版本:  0.2.18

### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/2823.html
2. 选择分卷：全部
3. 错误信息：
![Snipaste_2024-07-04_21-48-07](https://github.com/Montaro2017/bili_novel_packer/assets/114563458/d585f577-06f9-4ae2-a35a-d488aae6bd27)

貌似只有这一部加载不出来目录，我试了其他几本漫画和小说都是正常的。

**Comment by Montaro2017** [comment]
网页结构错误 不予解决
![image](https://github.com/Montaro2017/bili_novel_packer/assets/35142778/3efa5a6e-9b6d-4924-b45c-d6ec4314b96b)
