### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by yuduotianguang** [Montaro2017/bili_novel_packer#40]
Null check operator used on a null value
#0      BiliNovelSource._getChapterPage (package:bili_novel_packer/light_novel/bili_novel/bili_novel_source.dart:216)
<asynchronous suspension>
#1      BiliNovelSource.getNovelChapter (package:bili_novel_packer/light_novel/bili_novel/bili_novel_source.dart:129)
<asynchronous suspension>
#2      NovelPacker._resolveChapter (package:bili_novel_packer/novel_packer.dart:143)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#4      NovelPacker._combineVolume (package:bili_novel_packer/novel_packer.dart:112)
<asynchronous suspension>
#5      NovelPacker.pack (package:bili_novel_packer/novel_packer.dart:82)
<asynchronous suspension>
#6      start (file:///d:/workdir/bili_novel_packer/bin/main.dart:38)
<asynchronous suspension>
#7      main (file:///d:/workdir/bili_novel_packer/bin/main.dart:14)
<asynchronous suspension>

运行出错，按回车键退出.(0.2.19)

这个是哔哩的出错，下面是文库的出错

Exception: Cloudflare Error
#0      WenkuNovelSource._getNovelChapter.<anonymous closure> (package:bili_novel_packer/light_novel/wenku_novel/wenku_novel_source.dart:144)
<asynchronous suspension>
#1      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#2      WenkuNovelSource._getNovelChapter (package:bili_novel_packer/light_novel/wenku_novel/wenku_novel_source.dart:132)
<asynchronous suspension>
#3      RetryOptions.retry (package:retry/retry.dart:131)
<asynchronous suspension>
#4      NovelPacker._resolveChapter (package:bili_novel_packer/novel_packer.dart:143)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#6      NovelPacker._combineVolume (package:bili_novel_packer/novel_packer.dart:112)
<asynchronous suspension>
#7      NovelPacker.pack (package:bili_novel_packer/novel_packer.dart:82)
<asynchronous suspension>
#8      start (file:///d:/workdir/bili_novel_packer/bin/main.dart:38)
<asynchronous suspension>
#9      main (file:///d:/workdir/bili_novel_packer/bin/main.dart:14)
<asynchronous suspension>

运行出错，按回车键退出.(0.2.19)

**Comment by Montaro2017** [comment]
提交BUG请使用Bug Report模板，否则直接关闭
