### ISSUE TITLE
[BUG] 连续下载多卷报错

### ISSUE THREAD

**Issue by wulei1997** [Montaro2017/bili_novel_packer#42]
### 使用版本
使用版本:  0.2.19

### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/2139.html
2. 选择分卷：全部
3. 错误信息：错误信息截图
<img width="720" alt="Snipaste_2024-09-18_12-23-30" src="https://github.com/user-attachments/assets/c1456d62-44d3-409a-bcc6-ecd8f691962a">

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息

**Comment by wulei1997** [comment]
还有下载完一本所有章节后一定要退出吗？不能继续下载

**Comment by Montaro2017** [comment]
多试几次，偶尔会抽风

**Comment by wulei1997** [comment]
> 多试几次，偶尔会抽风

一到晚上用不了

**Comment by c870620096** [comment]
现在是普遍用不了了
