### ISSUE TITLE
[BUG] 小说只有一卷时会报错

### ISSUE THREAD

**Issue by wulei1997** [Montaro2017/bili_novel_packer#43]
### 使用版本
使用版本:  0.2.19
### 复现步骤

1. 输入网址：https://www.bilinovel.com/novel/4287.html
2. 选择分卷：全部
3. 错误信息：错误信息截图
<img width="720" alt="Snipaste_2024-09-18_19-48-00" src="https://github.com/user-attachments/assets/a2c62b9d-d97f-4d10-b85b-3de9bd6737c9">

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息

**Comment by Montaro2017** [comment]
实测没问题
