### ISSUE TITLE
[BUG] 到现在为止 一直不能用

### ISSUE THREAD

**Issue by kidzhende** [Montaro2017/bili_novel_packer#44]
bili_novel_packer 环境搞了一遍又一遍 最后也是报错
![Clip_2024-09-27_13-59-38](https://github.com/user-attachments/assets/5c9117ab-a59f-4fd5-9ae7-b909fd088549)
这玩意封装不彻底，脱离不了开发环境吧，下载的exe 用几次一直报错
自己编译了报下面这个错
![Clip_2024-09-27_13-59-38](https://github.com/user-attachments/assets/bc563d32-149f-4b63-9713-d780c4d1300f)
作者大大，你找个没有你现在开发环境的电脑用你封装的exe试一下 绝对报错跑不了

**Comment by Montaro2017** [comment]
我在家里和公司电脑都能用

**Comment by kidzhende** [comment]
你是什么系统...

**Comment by wulei1997** [comment]
用不了

**Comment by Montaro2017** [comment]
用新版在跑一次，添加了日志记录

**Comment by Montaro2017** [comment]
@kidzhende @2655196510 @wulei1997 用`0.2.22-rc1`试试

**Comment by 2655196510** [comment]
好像还是不行
![捕获](https://github.com/user-attachments/assets/e4a540d4-af3c-4651-8c03-b3fbf4a541ac)
[bili_novel.log](https://github.com/user-attachments/files/17259585/bili_novel.log)

**Comment by kidzhende** [comment]
我这能正常下载了，大体看了下epub 还算正常暂未有其他错误，但日志文件里的内容貌似还有报错 看不懂，你看下
[bili_novel.log](https://github.com/user-attachments/files/17260279/bili_novel.log)

**Comment by 2655196510** [comment]
啊？就我倒霉吗

**Comment by kidzhende** [comment]
测试站 https://www.linovelib.com/ 另一个没试

**Comment by 2655196510** [comment]
文库比较好爬

**Comment by kidzhende** [comment]
我试试文库

**Comment by kidzhende** [comment]
测试 https://www.wenku8.net/book/1829.htm  报错
![PixPin_2024-10-04_22-53-42](https://github.com/user-attachments/assets/10bc7428-24d9-4b49-ae5a-a5f378afb13d)

**Comment by 2655196510** [comment]
哈哈

**Comment by 2655196510** [comment]
就算不用这个软件也可以免费下载吧

**Comment by kidzhende** [comment]
测试链接有错 换其他的 文本内容正常 插图挂了
![Clip_2024-10-04_23-02-42](https://github.com/user-attachments/assets/c19d284e-9160-4c0a-b5c6-0bfcc971e599)

**Comment by kidzhende** [comment]
浏览器正常浏览可以 ....

**Comment by kidzhende** [comment]
下完之后访问。。。。
![Clip_2024-10-04_23-04-24](https://github.com/user-attachments/assets/5d067002-2880-468c-b766-2bffafedb99f)

**Comment by kidzhende** [comment]
被屏蔽了

**Comment by Montaro2017** [comment]
> 我这能正常下载了，大体看了下epub 还算正常暂未有其他错误，但日志文件里的内容貌似还有报错 看不懂，你看下 [bili_novel.log](https://github.com/user-attachments/files/17260279/bili_novel.log)

你这个没什么问题

**Comment by Montaro2017** [comment]
> 测试 https://www.wenku8.net/book/1829.htm 报错 ![PixPin_2024-10-04_22-53-42](https://private-user-images.githubusercontent.com/23150987/373687653-10bc7428-24d9-4b49-ae5a-a5f378afb13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNzg4NzcsIm5iZiI6MTcyODE3ODU3NywicGF0aCI6Ii8yMzE1MDk4Ny8zNzM2ODc2NTMtMTBiYzc0MjgtMjRkOS00YjQ5LWFlNWEtYTVmMzc4YWZiMTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAxMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MTEwNmNmNDVhOTQ0ZjUzYTViOWVkOWFkYTQxMzdlZTZkODEzOGIxY2U2ZWVhZWE2MDkyNTY1NGMzNTJjYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8_f80lhEnQHiK0Iecv5R49Fe3wHS7x9I8Vc_EMtYrE0)

`v0.2.22-rc2`已修复这个问题

**Comment by kidzhende** [comment]
今天突然爆这个错
![PixPin_2024-10-07_14-40-53](https://github.com/user-attachments/assets/a50237c5-b71a-455b-89bc-c86be51050da)

**Comment by kidzhende** [comment]
好像是 小说文件名含有特殊符号，导致最后保存文件时路径失效 但分卷保存没问题啊...

**Comment by Montaro2017** [comment]
> 好像是 小说文件名含有特殊符号，导致最后保存文件时路径失效 但分卷保存没问题啊...

这个问题已解决，下个版本发布

**Comment by 2655196510** [comment]
为啥输入双数就卡住了，不弹出选项是否合卷
<img width="862" alt="屏幕截图 2024-10-08 145802" src="https://github.com/user-attachments/assets/2f50031e-3465-462e-81a0-f8a17283c9ed">
<img width="864" alt="屏幕截图 2024-10-08 145938" src="https://github.com/user-attachments/assets/31c4f75a-1f4c-4451-aa29-6ba97234b2f2">

**Comment by 2655196510** [comment]
选择全部下载没啥问题，就单独下载双数卷就卡住

**Comment by Montaro2017** [comment]
> 选择全部下载没啥问题，就单独下载双数卷就卡住

输入数字的时候后面再打个空格试下

**Comment by 2655196510** [comment]
nb

**Comment by 2655196510** [comment]
可以了

**Comment by 2655196510** [comment]
<img width="865" alt="屏幕截图 2024-10-08 150648" src="https://github.com/user-attachments/assets/70d52584-5da5-4f06-b275-0d2114bb1d90">
