### ISSUE TITLE
说个昨天意外遇到的情况

### ISSUE THREAD

**Issue by kidzhende** [Montaro2017/bili_novel_packer#45]
https://www.linovelib.com/novel/23.html
昨天采集的这个，用分卷方式，然后发现，文件夹内出现个文件夹
![Clip_2024-10-10_09-35-05](https://github.com/user-attachments/assets/4f57d034-eeea-489b-90b4-fd011d4852e0)
最终发现，是这个卷名导致出现又一层文件夹，而且里面那一卷，文件名只有半截，文件夹的名是/前半截，后半截成立文件名……

**Comment by kidzhende** [comment]
![Clip_2024-10-10_09-39-49](https://github.com/user-attachments/assets/8b45ef7c-28e5-425e-89e6-d0226e25af31)
![Clip_2024-10-10_09-40-06](https://github.com/user-attachments/assets/e555ac7d-bb02-4217-af0f-ee246943f6d9)

**Comment by Montaro2017** [comment]
下个版本修复

**Comment by kidzhende** [comment]
![Clip_2024-10-11_16-20-18](https://github.com/user-attachments/assets/beeeb133-a38a-4dcd-9973-71bcd838a33f)
这是个什么错？
