### ISSUE TITLE
0.1.2-m1及0.1.1无法下载小说第二卷及之后的

### ISSUE THREAD

**Issue by svdbnm** [Montaro2017/bili_novel_packer#5]
0.1.2-m1及0.1.1无法下载小说第二卷及之后的小说，单独下载和下载全部好像不行，打包过程中一会直接闪退

**Comment by svdbnm** [comment]
例子：https://w.linovelib.com/novel/3523.html

**Comment by Montaro2017** [comment]
网站图片改成懒加载了，0.1.2-M2版本已解决
https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/0.1.2-M2
