### ISSUE TITLE
下载章节很多的卷时可能被ban

### ISSUE THREAD

**Issue by szlysms** [Montaro2017/bili_novel_packer#51]
### 使用版本
使用版本:  0.2.26

### 复现步骤
使用程序下载小说3928，由于第一卷章节过多，下到后面会显示错误，log显示在快下完的时候被ban
也许能加一个从指定章节开始下载的参数或功能
[bili_novel.log](https://github.com/user-attachments/files/17775884/bili_novel.log)

**Comment by Montaro2017** [comment]
看起来是IP被ban了

**Comment by Montaro2017** [comment]
目前只能以龟速下载，太快了就会被ban了
