### ISSUE TITLE
[BUG] 在此输入问题描述

### ISSUE THREAD

**Issue by Lin1nan279** [Montaro2017/bili_novel_packer#52]
### 使用版本
使用版本:  0.2.26

### 复现步骤

Null check operator used on a null value
#0      BiliNovelSource.getNovel (package:bili_novel_packer/light_novel/bili_novel/bili_novel_source.dart:52)
<asynchronous suspension>
#1      NovelPacker.getNovel.<anonymous closure> (package:bili_novel_packer/novel_packer.dart:58)
<asynchronous suspension>
#2      NovelPacker.init (package:bili_novel_packer/novel_packer.dart:50)
<asynchronous suspension>
#3      start (file:///d:/myprojects/bili_novel_packer/bin/main.dart:39)
<asynchronous suspension>
#4      main (file:///d:/myprojects/bili_novel_packer/bin/main.dart:15)
<asynchronous suspension>

请问下这个是什么情况？下载一本突然变成了这样，然后再重新打开软件也下载不了了

**Comment by Montaro2017** [comment]
IP被ban

**Comment by Lin1nan279** [comment]
T T只下了1本就被BAN掉了，這麼迅速
