### ISSUE TITLE
[BUG] 今日使用0.2.27

### ISSUE THREAD

**Issue by aaron988025** [Montaro2017/bili_novel_packer#56]
### 使用版本
使用版本:  0.2.27

### 复现步骤

1. 输入网址： https://tw.linovelib.com/novel/2699.html
2. 选择分卷：全部
3. 错误信息：如下圖

![image](https://github.com/user-attachments/assets/4f438ae4-7153-4c7b-9114-533003208be5)

**Comment by Montaro2017** [comment]
实测没问题，建议过一段时间重试
