### ISSUE TITLE
封面問題

### ISSUE THREAD

**Issue by watercup0926** [Montaro2017/bili_novel_packer#9]
前面先道歉一下，如果讓你不高興了請忽略我
近期使用下來都很完美，唯一美中不足的地方就是檔案的封面不一定是小說的封面，雖說這個完全不急，可以等重構完後再處理，真的非常抱歉

**Comment by Montaro2017** [comment]
目前没有比较好的解决方法，近期也没有重构打算
现在的方案是按图片比例选择最接近4比3同时比较靠前的图片
有什么好的思路可以提出

**Comment by watercup0926** [comment]
也許資源到齊後最前面的圖片?

**Comment by Montaro2017** [comment]
尝试下新版本
https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/0.1.3-M1
